[project]
name = "har-analyzer"
version = "0.1.0"
description = "Analyzer for the .har file"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "jsonschema[format]>=4.25.0",
]
